Failed to execute script 'USBLogger' due to unhandled exception: winmgmts:.Win32_USBHub

Traceback (most recent call last):
  File "wmi.py", line 1209, in __getattr__
  File "wmi.py", line 1220, in _cached_classes
  File "<COMObject winmgmts:>", line 2, in Get
  File "win32com\client\dynamic.py", line 366, in _ApplyTypes_
pywintypes.com_error: (-2147352567, 'Une exception s’est produite.', (0, 'SWbemServicesEx', 'Non trouvé ', None, 0, -2147217406), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "USBLogger.py", line 200, in <module>
    monitor_usb()
  File "USBLogger.py", line 172, in monitor_usb
    watcher_in = c.watch_for(notification_type = "Creation", wmi_class="Win32_USBHub")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "wmi.py", line 1170, in watch_for
  File "wmi.py", line 1211, in __getattr__
  File "win32com\client\dynamic.py", line 638, in __getattr__
AttributeError: winmgmts:.Win32_USBHub